### ISSUE TITLE
Can you share your yolov3.tflite file??

### ISSUE THREAD

**Issue by a41888936** [butterfly-coder/TFlite-People-Counter-Android#1]
Thanks for sharing your project..

In your asset folder there is only detect.tflite.

If you can't, can you give some tips to make yolvo3 tflite???

**Comment by butterfly-coder** [comment]
@a41888936
Sorry for delay response.
I have pushed yolov3.tflite file.

**Comment by butterfly-coder** [comment]
Sorry, Accidentally closed issue

**Comment by butterfly-coder** [comment]
@a41888936 

Closing as adding yolov tflite file.
